version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/public/:/usr/share/nginx/
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
  app:
    build:
      context: app
      dockerfile: ./Dockerfile
    container_name: app_homework_2
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"