version: "3.9"

services:
  nginx:
    image: nginx:latest
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80

  django:
    build:
      context: bank_accounting
      dockerfile: Dockerfile
    container_name: app_homework_3
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
    entrypoint: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    hostname: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hw_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT 1;' | psql -U postgres -d hw_db" ]
      interval: 3s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    driver: local
